sudo: required
language: rust

matrix:
  include:
    - rust: stable
      env:
      - LABEL="stable"
      script:
      - ./ci/stable.sh
    - rust: stable
      env:
      - LABEL="no-std"
      script:
      - ./ci/thumbv6m.sh
